# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd4880243516af52fdb095777a6049bba94e565ee4d20022ecbbad10d2558a174fe5d161beb93e0a4dd484d94098bef0c496d871ba63d4d42d16b0dc94c581b

test:
  secret_key_base: aa794569182a946ee217c2e9a616fb1458f3423c6b6e58a6400bb6dec9981324263f346b4b157aa459169e31ee8737786fe4e2e8849852adff6cec89fd094e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
